/**
 * Generate TypeScript types from Swagger/OpenAPI specification
 * 
 * This script fetches the Swagger JSON from the backend server and generates
 * TypeScript type definitions that can be used in the frontend.
 * 
 * Usage:
 *   1. Make sure the backend server is running
 *   2. Run: npm run generate:types
 *   3. The generated types will be saved to frontend/src/types/generated/swagger.d.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

// Get __dirname equivalent for ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Use createRequire to load CommonJS modules in ES module context
const require = createRequire(import.meta.url);

// Load swagger spec
const swaggerModule = require('../backend/src/config/swagger');
const swaggerSpec = swaggerModule.swaggerSpec;

// Configuration
const OUTPUT_DIR = path.join(__dirname, '../frontend/src/types/generated');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'swagger.d.ts');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

/**
 * Convert Swagger schema to TypeScript type definition
 */
function swaggerToTypeScript(schema: any, typeName: string): string {
  // Handle allOf case (like BookDetail) - check this first
  if (schema.allOf && Array.isArray(schema.allOf)) {
    const types: string[] = [];
    for (const item of schema.allOf) {
      if (item.$ref) {
        types.push(item.$ref.split('/').pop());
      } else if (item.properties) {
        // Generate inline interface for the additional properties
        const props: string[] = [];
        const required = item.required || [];
        for (const [key, value] of Object.entries(item.properties)) {
          const prop = value as any;
          const isRequired = required.includes(key);
          const optional = isRequired ? '' : '?';
          const type = getTypeScriptType(prop, key);
          props.push(`  ${key}${optional}: ${type};`);
        }
        if (props.length > 0) {
          types.push(`{\n${props.join('\n')}\n}`);
        }
      }
    }
    if (types.length > 0) {
      return `export type ${typeName} = ${types.join(' & ')};`;
    }
  }

  if (!schema || !schema.properties) {
    return `export type ${typeName} = any;`;
  }

  const properties: string[] = [];
  const required = schema.required || [];

  for (const [key, value] of Object.entries(schema.properties)) {
    const prop = value as any;
    const isRequired = required.includes(key);
    const optional = isRequired ? '' : '?';
    const type = getTypeScriptType(prop, key);
    properties.push(`  ${key}${optional}: ${type};`);
  }

  return `export interface ${typeName} {\n${properties.join('\n')}\n}`;
}

/**
 * Convert Swagger type to TypeScript type
 */
function getTypeScriptType(prop: any, propName: string): string {
  if (prop.$ref) {
    // Reference to another schema
    const refName = prop.$ref.split('/').pop();
    return refName || 'any';
  }

  if (prop.allOf && Array.isArray(prop.allOf)) {
    // Handle allOf (extends)
    const types = prop.allOf.map((item: any) => {
      if (item.$ref) {
        return item.$ref.split('/').pop();
      }
      return swaggerToTypeScript(item, 'Temp');
    });
    return types.join(' & ');
  }

  if (prop.type === 'array') {
    const itemType = prop.items ? getTypeScriptType(prop.items, 'item') : 'any';
    return `${itemType}[]`;
  }

  if (prop.type === 'object' && prop.properties) {
    // Inline object type
    const inlineType = swaggerToTypeScript(prop, 'Inline');
    return inlineType.replace(/export interface Inline \{/, '{').replace(/\n\}$/, '\n}');
  }

  // Map Swagger types to TypeScript types
  const typeMap: Record<string, string> = {
    string: 'string',
    number: 'number',
    integer: 'number',
    boolean: 'boolean',
    null: 'null',
  };

  let tsType = typeMap[prop.type] || 'any';

  // Handle nullable
  if (prop.nullable || prop.type === 'null') {
    tsType = `${tsType} | null`;
  }

  // Handle format
  if (prop.format === 'date' || prop.format === 'date-time') {
    tsType = 'string'; // Dates are typically strings in JSON
  }

  return tsType;
}

/**
 * Generate types from Swagger spec
 */
function generateTypes(): void {
  console.log('Generating TypeScript types from Swagger specification...\n');

  const spec = swaggerSpec as any;
  const schemas = spec.components?.schemas || {};
  const typeDefinitions: string[] = [];

  // Add header comment
  typeDefinitions.push('/**');
  typeDefinitions.push(' * Auto-generated TypeScript types from Swagger/OpenAPI specification');
  typeDefinitions.push(' * ');
  typeDefinitions.push(' * DO NOT EDIT THIS FILE MANUALLY');
  typeDefinitions.push(' * This file is generated automatically from the Swagger schema');
  typeDefinitions.push(' * Run "npm run generate:types" to regenerate');
  typeDefinitions.push(' */\n');

  // Generate types for each schema
  for (const [schemaName, schema] of Object.entries(schemas)) {
    const schemaObj = schema as any;
    const typeDef = swaggerToTypeScript(schemaObj, schemaName);
    typeDefinitions.push(typeDef);
    typeDefinitions.push('');
  }

  // Generate API response types (only if not already defined in schemas)
  if (!schemas.ApiSuccess && !schemas.ApiError) {
    typeDefinitions.push('// API Response wrappers');
    typeDefinitions.push('export interface ApiSuccess<T> {');
    typeDefinitions.push('  success: true;');
    typeDefinitions.push('  data: T;');
    typeDefinitions.push('}\n');

    typeDefinitions.push('export interface ApiError {');
    typeDefinitions.push('  success: false;');
    typeDefinitions.push('  error: {');
    typeDefinitions.push('    code: string;');
    typeDefinitions.push('    message: string;');
    typeDefinitions.push('    details?: any;');
    typeDefinitions.push('  };');
    typeDefinitions.push('}\n');

    typeDefinitions.push('export type ApiResponse<T> = ApiSuccess<T> | ApiError;');
  }

  // Write to file
  const content = typeDefinitions.join('\n');
  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');

  console.log(`✓ Types generated successfully!`);
  console.log(`  Output: ${OUTPUT_FILE}`);
  console.log(`  Generated ${Object.keys(schemas).length} schema types\n`);
}

// Run if executed directly
if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith('generate-types-from-swagger.ts')) {
  try {
    generateTypes();
  } catch (error) {
    console.error('Error generating types:', error);
    process.exit(1);
  }
}

export { generateTypes };

